// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:string):Promise<void>;

export function GetTasks():Promise<Array<main.Task>>;

export function GetUsername():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RemoveTask(arg1:number):Promise<void>;

export function SetUsername(arg1:string):Promise<void>;
