// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';

export function AddProfile(arg1:string):Promise<number>;

export function AddTask(arg1:number,arg2:string,arg3:any,arg4:boolean):Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetActiveTasks(arg1:number):Promise<Array<repository.Task>>;

export function GetCompletedTasks(arg1:number):Promise<Array<repository.Task>>;

export function GetProfile(arg1:number):Promise<repository.Profile>;

export function GetProfiles():Promise<Array<repository.Profile>>;

export function Greet(arg1:string):Promise<string>;

export function UpdateProfile(arg1:number,arg2:string):Promise<void>;

export function UpdateTask(arg1:number,arg2:string,arg3:any):Promise<void>;

export function UpdateTaskPriority(arg1:number,arg2:boolean):Promise<void>;

export function UpdateTaskStatus(arg1:number,arg2:string):Promise<void>;
