// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2) {
  return window['go']['main']['App']['AddTask'](arg1, arg2);
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveTask(arg1) {
  return window['go']['main']['App']['RemoveTask'](arg1);
}

export function SetUsername(arg1) {
  return window['go']['main']['App']['SetUsername'](arg1);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1, arg2);
}
