// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['main']['App']['AddProfile'](arg1);
}

export function AddTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3, arg4);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetActiveTasks(arg1) {
  return window['go']['main']['App']['GetActiveTasks'](arg1);
}

export function GetCompletedTasks(arg1) {
  return window['go']['main']['App']['GetCompletedTasks'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}

export function UpdateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3);
}

export function UpdateTaskPriority(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskPriority'](arg1, arg2);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1, arg2);
}
